Add all logos
eiffel-community/community pull request #120
Opened 2021-11-05 16:07 UTC by m-linner-ericsson

### Applicable Issues
Action item from TC

### Description of the Change
Documenting how images should be handled within the Eiffel Community

### Alternate Designs
N/A

### Benefits
Guidelines for handling graphical images

### Possible Drawbacks
N/A

### Sign-off

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

Signed-off-by: Mattias Linner <mattias.linner@ericsson.com>

2021-11-10 14:52 UTC, m-linner-ericsson commented
This could be too vague for a recommendation but let us see what you think

2021-11-10 16:12 UTC, e-backmark-ericsson commented
In the logo section I believe you should include a link to working_with_community-logos.md

2021-11-16 09:09 UTC, m-linner-ericsson commented
> 
> 
> In the logo section I believe you should include a link to working_with_community-logos.md

Fixed in f8922dc

2021-11-16 12:46 UTC, e-backmark-ericsson approved these changes

2021-11-16 12:55 UTC, magnusbaeck requested changes
Two tiny grammatical nits that we fix as well fix, otherwise LGTM.

2021-11-16 12:55 UTC, magnusbaeck commented on howtos/how-to-handle-graphical-images.md
> +When creating an graphical image, for use within the Eiffel community, add the original file to the repository along with any needed format. To help future updates, place a README in the directory ex
When creating **a** graphical image

2021-11-16 12:55 UTC, magnusbaeck commented on howtos/how-to-handle-graphical-images.md
> +Both the Eiffel protocol repository and Sepia have used [Inkscape](https://inkscape.org/). Inkscape saves its images in a variant of SVG that most browsers can render directly. When saving an image y
Always add the image as **an** Inkscape

2021-11-29 09:44 UTC, m-linner-ericsson commented on howtos/how-to-handle-graphical-images.md
> +When creating an graphical image, for use within the Eiffel community, add the original file to the repository along with any needed format. To help future updates, place a README in the directory ex
Fixed in 7d3d01b

2021-11-29 09:44 UTC, m-linner-ericsson commented on howtos/how-to-handle-graphical-images.md
> +Both the Eiffel protocol repository and Sepia have used [Inkscape](https://inkscape.org/). Inkscape saves its images in a variant of SVG that most browsers can render directly. When saving an image y
Fixed in 7d3d01b

2021-11-30 19:19 UTC, magnusbaeck approved these changes

2021-12-02 12:58 UTC, t-persson approved these changes

2021-12-02 14:43 UTC, merged