GOVERNANCE.md: Remove David Westberg from TC member table
eiffel-community/community pull request #126
Opened 2022-01-10 15:50 UTC by magnusbaeck

### Applicable Issues
N/A

### Description of the Change
David has chosen to leave the technical committee so he should be removed from the table of TC members.

### Alternate Designs
Considered leaving breadcrumbs to indicate that he was duly elected but chose to leave, but figured that we have the git history for that. The TC membership table should reflect the current reality.

### Benefits
Governance document reflects reality.

### Possible Drawbacks
None

### Sign-off

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I    have the right to submit it under the open source license    indicated in the file; or

(b) The contribution is based upon previous work that, to the best    of my knowledge, is covered under an appropriate open source    license and I have the right under that license to submit that    work with modifications, whether created in whole or in part    by me, under the same open source license (unless I am    permitted to submit under a different license), as indicated    in the file; or

(c) The contribution was provided directly to me by some other    person who certified (a), (b) or (c) and I have not modified    it.

(d) I understand and agree that this project and the contribution    are public and that a record of the contribution (including all    personal information I submit with it, including my sign-off) is    maintained indefinitely and may be redistributed consistent with    this project or the open source license(s) involved.

Signed-off-by: Magnus Bäck \<magnus.back@axis.com>

2022-01-10 16:02 UTC, e-backmark-ericsson requested changes
For traceability maybe it would be better to keep his name in the table and instead show that he left his position in advance in December 2021?

2022-01-10 16:03 UTC, e-backmark-ericsson approved these changes
Changed my mind. Change is accepted, with your comment on the issue in mind :)

2022-01-11 08:55 UTC, m-linner-ericsson approved these changes

2022-01-11 12:17 UTC, t-persson approved these changes

2022-01-11 12:38 UTC, merged