GOVERNANCE.md: Update with new TC
eiffel-community/community pull request #133
Opened 2022-05-19 10:08 UTC by magnusbaeck

### Applicable Issues
N/A

### Description of the Change
The TC elections checklist is completed and the TC and TC chairs tables are updated with new dates and the new TC member Azeem Ahmad.

Also updated the company for Tobias and Magnus whose employer is Axis Communications, not Axis which is the holding company of the former.

### Alternate Designs
None.

### Benefits
Up to date TC information.

### Possible Drawbacks
None.

### Sign-off

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I    have the right to submit it under the open source license    indicated in the file; or

(b) The contribution is based upon previous work that, to the best    of my knowledge, is covered under an appropriate open source    license and I have the right under that license to submit that    work with modifications, whether created in whole or in part    by me, under the same open source license (unless I am    permitted to submit under a different license), as indicated    in the file; or

(c) The contribution was provided directly to me by some other    person who certified (a), (b) or (c) and I have not modified    it.

(d) I understand and agree that this project and the contribution    are public and that a record of the contribution (including all    personal information I submit with it, including my sign-off) is    maintained indefinitely and may be redistributed consistent with    this project or the open source license(s) involved.

Signed-off-by: Magnus Bäck \<magnus.back@axis.com>

2022-05-19 10:34 UTC, t-persson approved these changes

2022-05-19 14:16 UTC, m-linner-ericsson requested changes
I thought that we only should tick the boxes we have actually done.

2022-05-23 06:21 UTC, m-linner-ericsson approved these changes

2022-05-23 07:03 UTC, e-backmark-ericsson approved these changes

2022-05-23 07:22 UTC, t-persson approved these changes

2022-05-23 07:24 UTC, merged