Update introduction-of-a-new-tc-member.md
eiffel-community/community pull request #155
Opened 2022-12-12 13:02 UTC by e-backmark-ericsson

### Applicable Issues
Fixes #154 

### Description of the Change
The onboarding checklist for new TC members is out-of-date. This PR fixes that.

### Alternate Designs
None

### Benefits
Checklist up-to-date

### Possible Drawbacks
None

### Sign-off
Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

Signed-off-by: Emil Bäckmark <emil.backmark@ericsson.com>

2022-12-12 13:06 UTC, e-backmark-ericsson commented on howtos/introduction-of-a-new-tc-member.md
> +- Become an owner (?) of each maintainer Google Group in the [members list](https://groups.google.com/g/eiffel-.../members)
This needs to be sorted out and updated before merging this PR

2022-12-19 07:43 UTC, magnusbaeck requested changes

2022-12-19 07:43 UTC, magnusbaeck commented on howtos/introduction-of-a-new-tc-member.md
> +
```suggestion
- Become an Admin in the [TC-managed GitHub projects](https://github.com/orgs/eiffel-community/projects).
```

2022-12-19 14:44 UTC, magnusbaeck commented
While you're at it, perhaps you can add an item for the following, for which we currently have a draft issue in the TC board?

> Add item on new-TC-member checklist to enable some kind of notification (immediate and/or digest) of Dependabot alerts.

2022-12-20 15:47 UTC, e-backmark-ericsson commented
> While you're at it, perhaps you can add an item for the following, for which we currently have a draft issue in the TC board?
> 
> > Add item on new-TC-member checklist to enable some kind of notification (immediate and/or digest) of Dependabot alerts.

Yes. Done now.

2022-12-20 15:47 UTC, e-backmark-ericsson commented on howtos/introduction-of-a-new-tc-member.md
> +- Become an owner (?) of each maintainer Google Group in the [members list](https://groups.google.com/g/eiffel-.../members)
It was decided on the last TC meeting that we should not continue using Google groups for the maintainers. At least not demanded from TC and not tightly connected to the GitHub repos. Updates to PROJECTS.md will happen through another issue/PR but we remove this statement here now.

2023-01-03 08:55 UTC, magnusbaeck approved these changes
We could add an item about adding the new member to the private TC Slack channel.

This checklist is getting awfully long. We should consider converting it into an issue template with checkboxes.

2023-01-04 15:40 UTC, e-backmark-ericsson commented
> We could add an item about adding the new member to the private TC Slack channel.
Done

> This checklist is getting awfully long. We should consider converting it into an issue template with checkboxes.
I believe one could easily just copy this whole document into the new issue, select each bullet list and press "Add a task list"

2023-01-04 15:41 UTC, magnusbaeck approved these changes

2023-01-09 07:48 UTC, t-persson approved these changes

2023-01-09 07:51 UTC, merged