Add new projects for CDEvents interaction
eiffel-community/community pull request #163
Opened 2023-01-26 10:20 UTC by e-backmark-ericsson

### Applicable Issues
Fixes #161 
Fixes #162 

### Description of the Change
Two new projects are added to PROJECTS.md, namely eiffel-demo-cdevents and eiffel-translator-cdevents

### Alternate Designs
None

### Benefits
Enables us to implement integrations with the CDEvents protocol

### Possible Drawbacks
None

### Sign-off
Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

Signed-off-by: Emil Bäckmark emil.backmark@ericsson.com

2023-01-26 16:22 UTC, magnusbaeck requested changes

2023-01-26 16:22 UTC, magnusbaeck commented on PROJECTS.md
> +| [Eiffel Translator CDEvents](https://github.com/eiffel-community/eiffel-translator-cdevents) | A translator for events between the Eiffel event protocol and the [CDEvents protocol](https://cdevents
```suggestion
| [Eiffel Translator CDEvents](https://github.com/eiffel-community/eiffel-translator-cdevents) | A translator for events between the Eiffel event protocol and the [CDEvents protocol](https://cdevents.dev/docs/). | [eiffel-cdevents-maintainers](https://github.com/orgs/eiffel-community/teams/eiffel-cdevents-maintainers) | *Not Available* | [Sandbox](./PROJECT_LIFECYCLE.md#stage-sandbox) |
```

2023-01-27 06:44 UTC, e-backmark-ericsson commented on PROJECTS.md
> +| [Eiffel Translator CDEvents](https://github.com/eiffel-community/eiffel-translator-cdevents) | A translator for events between the Eiffel event protocol and the [CDEvents protocol](https://cdevents
Of course. Copy/paste fault.

2023-01-27 07:28 UTC, magnusbaeck approved these changes

2023-01-27 08:00 UTC, m-linner-ericsson approved these changes

2023-01-27 08:18 UTC, merged