Update GOVERNANCE.md on election details
eiffel-community/community pull request #186
Opened 2024-01-04 08:56 UTC by e-backmark-ericsson

### Applicable Issues
Closes #164 

### Description of the Change
Updates to the GOVERNANCE.md document to clarify the TC election process, including the review of the eligible candidates list. This PR goes hand-in-hand with the updates to the ELECTIONS.md document seen [here](https://github.com/eiffel-community/community/commit/63b4e9763ca180b99c1335e67dafeb644f4d680c) and [here](https://github.com/eiffel-community/community/commit/824a2cc97752b262e82979bfa5fb260378182662) (updated through HackMD).

### Alternate Designs
N/A

### Benefits
Clearer election process, and no duplication 

### Possible Drawbacks
none

### Sign-off
Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

Signed-off-by: Emil Bäckmark emil.backmark@ericsson.com

2024-01-04 09:36 UTC, magnusbaeck requested changes
Apart from the language nits, the linked issue talks about the eligibility exception process but I can't see any changes related to that in this PR.

2024-01-04 09:36 UTC, magnusbaeck commented on GOVERNANCE.md
> +1. Anyone who is a member to [Eiffel Community Maillist](https://groups.google.com/g/eiffel-community) is eligible to vote on Technical Committee Elections.
```suggestion
1. Anyone who is a member of the [Eiffel Community Maillist](https://groups.google.com/g/eiffel-community) is eligible to vote on Technical Committee Elections.
```

2024-01-04 09:36 UTC, magnusbaeck commented on GOVERNANCE.md
> +  * The list of eligible members is open for review for one to two weeks. Any changes to this list are managed by the Election Officers and informed to the Technical Committee before the nomination p
```suggestion
  * The list of eligible members is open for review for one to two weeks. Any changes to this list are managed by the Election Officers who inform the Technical Committee before the nomination phase starts.
```

2024-01-04 09:44 UTC, e-backmark-ericsson commented
I couldn't find any explicit exemption process mentioned in the elections document, so I thought the only thing was that the list of eligible candidates was sent for review to the community and then updated if any candidates are missing or faultily added there. Are there any other exemptions we should document?

2024-01-04 13:01 UTC, e-backmark-ericsson commented
Update the text on the eligible candidate list slightly. Please re-review.

2024-01-08 13:22 UTC, magnusbaeck requested changes
Found another language nit that we might as well fix, otherwise LGTM.

2024-01-08 14:20 UTC, magnusbaeck approved these changes

2024-01-10 12:30 UTC, m-linner-ericsson approved these changes

2024-01-11 07:40 UTC, merged