Update PROJECT_LIFECYCLE.md
eiffel-community/community pull request #55
Opened 2020-09-08 07:46 UTC by fredjn

### Applicable Issues
N/A

### Description of the Change
Added short sentence regarding naming convention for new projects

### Alternate Designs
N/A

### Benefits
Make it clear that there is no strictly enforced project naming convention

### Possible Drawbacks
A risk projects with confusing name being added

### Sign-off
Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

Signed-off-by: Fredrik Fristedt fredrik.fristedt@axis.com

2020-09-08 07:49 UTC, t-persson requested changes
Spellcheck

2020-09-08 07:49 UTC, t-persson commented on PROJECT_LIFECYCLE.md
> +names are encuraged.
```suggestion
names are encouraged. 
```

2020-09-08 07:49 UTC, t-persson commented on PROJECT_LIFECYCLE.md
> +Regarding project naming convenctions, the eiffel community enforces no name convention but meaningfull descriptive
```suggestion
Regarding project naming convenctions, the eiffel community enforces no name convention but meaningful descriptive 
```

2020-09-10 11:52 UTC, fdegir commented on PROJECT_LIFECYCLE.md
> +Regarding project naming convenctions, the eiffel community enforces no name convention but meaningful descriptive
```suggestion
Regarding project naming conventions, the Eiffel Community enforces no name convention but meaningful descriptive 
```

typo + capitals

2020-09-10 11:52 UTC, fdegir commented on PROJECT_LIFECYCLE.md
> +Regarding project naming convenctions, the eiffel community enforces no name convention but meaningful descriptive
as mentioned on Slack, I do not have a strong opinion about this so I vote 0/abstain from voting. ;)

2020-09-14 09:09 UTC, m-linner-ericsson reviewed
Good that we record this in writing. I don't have anything else to add except waiting for fix for Fatih comments

2020-09-14 12:08 UTC, d-stahl-ericsson approved these changes

2020-09-14 12:46 UTC, fdegir approved these changes

2020-09-14 12:47 UTC, m-linner-ericsson approved these changes

2020-09-14 20:00 UTC, sodero approved these changes

2020-09-15 05:27 UTC, t-persson approved these changes

2020-09-15 06:34 UTC, henning-roos approved these changes

2020-09-16 08:04 UTC, e-backmark-ericsson approved these changes

2020-09-16 10:58 UTC, k-hallen-ericsson approved these changes

2020-09-16 11:09 UTC, fdegir commented
This amendment to project lifecycle passes so the PR can be merged. Thanks all for the reviews.

Please also take a look at the [ETOS project proposal](https://github.com/eiffel-community/community/issues/57) and comment/vote on it accordingly.

2020-09-16 14:43 UTC, merged