Add requirement to send mail to Eiffel Community maillist
eiffel-community/community pull request #79
Opened 2020-11-18 09:20 UTC by fdegir

New project proposals and proposals to move projects to different
lifecycle stages should be announced on Eiffel Community maillist
in order to increase the visibility.

Once the project creation or project lifecycle process is concluded,
TC chair sends an email to Eiffel Community maillist and announce
the new project or the lifecycle stage to broader Eiffel Community.

### Applicable Issues

Closes AP from [TC meeting](https://hackmd.io/SCImga0nS1qSh3QvsEOAVQ?view#Action-Items).

### Description of the Change

Project proposals and lifecycle stage changes are handled via GitHub issues in Eiffel Community community repository, which is not monitored by broader community.
In order to increase the visibility, transparency and community participation, it is important to announce this type of changes to the community on Eiffel Community Maillist.

This commit updates project lifecycle document to require such mails to be sent to the maillist.

### Alternate Designs

N/A

### Benefits

Increased visibility, transparency, and community participation.

### Possible Drawbacks

N/A

### Sign-off

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

Signed-off-by: Fatih Degirmenci fatih.degirmenci@est.tech

2020-11-18 10:10 UTC, e-backmark-ericsson approved these changes

2020-11-18 21:51 UTC, sodero approved these changes

2020-11-19 05:37 UTC, d-stahl-ericsson requested changes

2020-11-19 05:37 UTC, d-stahl-ericsson commented on PROJECT_LIFECYCLE.md
> +sending an email in order to increase the visibility. The email should contain same information as the proposal
```suggestion
sending an email in order to increase the visibility. The email should contain the same information as the proposal
```

2020-11-19 05:37 UTC, d-stahl-ericsson commented on PROJECT_LIFECYCLE.md
> +in order to announce the creation of the project to broader community for increased visibility.
```suggestion
in order to announce the creation of the project to the broader community for increased visibility.
```

2020-11-19 05:37 UTC, d-stahl-ericsson commented on PROJECT_LIFECYCLE.md
> +in order to announce the changes to project lifecycle stage to broader community for increased visibility.
```suggestion
in order to announce the changes to project lifecycle stage to the broader community for increased visibility.
```

2020-11-19 07:53 UTC, m-linner-ericsson approved these changes

2020-11-23 11:36 UTC, d-stahl-ericsson approved these changes

2021-01-28 12:58 UTC, henning-roos approved these changes

2021-02-01 23:15 UTC, fredjn requested changes

2021-02-01 23:15 UTC, fredjn commented on PROJECT_LIFECYCLE.md
>  expected to follow same process as project creation by formally submitting their request on GitHub Eiffel
remove GitHub
```suggestion
expected to follow same process as project creation by formally submitting their request on Eiffel
```

2021-02-08 08:12 UTC, fredjn approved these changes

2021-02-08 08:22 UTC, merged